---
root: true
env:
    browser: true
    es6: true
    node: true

globals:
    graphql: false

parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 2020
    sourceType: module
    ecmaFeatures:
        experimentalObjectRestSpread: true
        jsx: true

settings:
    react:
        version: detect

extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:react-hooks/recommended
    - plugin:jsx-a11y/recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
    - plugin:import/errors
    - plugin:import/warnings
    - plugin:import/typescript
    - plugin:prettier/recommended
plugins:
    - '@typescript-eslint'
    - react
rules:
    no-console: off
    linebreak-style:
        - error
        - unix
    prefer-const: error
    '@typescript-eslint/explicit-module-boundary-types': off
